Adding bearer authentication support
youviewtv/SocketRocket pull request #1
Opened 2017-02-06 16:32 UTC by tmughal

This commit adds support for bearer authentication during the WebSocket handshake request.

2017-02-06 16:32 UTC, tmughal commented
@youviewtv/ios Please review

2017-02-06 17:29 UTC, wandeep approved these changes
+1 With minor comment for consideration - also any tests required for this change?

2017-02-06 17:29 UTC, wandeep commented on SocketRocket/SRWebSocket.m
> +                            [self didConnect];
Use weakSelf

2017-02-06 17:41 UTC, neildavis requested changes

2017-02-06 17:41 UTC, neildavis commented on SocketRocket/SRWebSocket.m
> +        if (responseCode == 401)
You should also check for a "WWW-Authenticate" HTTP header in the response identifying the "Bearer" scheme before relying on the authentication delegate to resolve. There are other reasons for 401 responses

2017-02-06 17:41 UTC, neildavis commented on SocketRocket/SRWebSocket.m
> +                            [self didConnect];
How do you resolve the infinite loop case when the delegate provides a token but you still receive a 401? If the token provided by the delegate does not resolve the authentication then the original 401 should be propogated to the caller. This is analagous to the HTTP middleware protocol 'fail fast' approach

2017-02-07 10:41 UTC, tmughal commented on SocketRocket/SRWebSocket.m
> +        if (responseCode == 401)
Funny enough, I was just thinking this last night. Made the change first thing this morning :)

2017-02-07 10:42 UTC, tmughal commented on SocketRocket/SRWebSocket.m
> +                            [self didConnect];
Shouldn't really need to use weakSelf as the block doesn't have a copy reference to it.

2017-02-07 12:48 UTC, tmughal commented
@youviewtv/ios Please review following changes.

This now allows additional headers to be set that will be used as part of the protocol handshake. Additionally, the error passed through the delegate will contain received headers as part of the user info when applicable.

2017-02-07 18:14 UTC, neildavis approved these changes
+1 with comment

2017-02-07 18:14 UTC, neildavis commented on SocketRocket/SRWebSocket.h
> +@property (nonatomic, strong) NSDictionary<NSString *, NSString *> *additionalHttpHeaders;
HTTP is capitalized everywhere else in the API

2017-02-08 15:03 UTC, faisalyv approved these changes
+1

2017-02-08 15:34 UTC, closed without merging